// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV81r8q5bv9vDFXVRLEVOFSxt72OjW1hM',
    appId: '1:94501489791:web:b600dc0eff72c48354434a',
    messagingSenderId: '94501489791',
    projectId: 'flutter-auth-431f3',
    authDomain: 'flutter-auth-431f3.firebaseapp.com',
    storageBucket: 'flutter-auth-431f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjbKnCfzhVEXhiTk1nUWvxkI4dEVOdzLk',
    appId: '1:94501489791:android:de7f6dad06b77ced54434a',
    messagingSenderId: '94501489791',
    projectId: 'flutter-auth-431f3',
    storageBucket: 'flutter-auth-431f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4hoDFt8ewbP0q0CNEiUlboer2f8AJJcs',
    appId: '1:94501489791:ios:50c641051dae636754434a',
    messagingSenderId: '94501489791',
    projectId: 'flutter-auth-431f3',
    storageBucket: 'flutter-auth-431f3.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4hoDFt8ewbP0q0CNEiUlboer2f8AJJcs',
    appId: '1:94501489791:ios:50c641051dae636754434a',
    messagingSenderId: '94501489791',
    projectId: 'flutter-auth-431f3',
    storageBucket: 'flutter-auth-431f3.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV81r8q5bv9vDFXVRLEVOFSxt72OjW1hM',
    appId: '1:94501489791:web:c7418c787863226e54434a',
    messagingSenderId: '94501489791',
    projectId: 'flutter-auth-431f3',
    authDomain: 'flutter-auth-431f3.firebaseapp.com',
    storageBucket: 'flutter-auth-431f3.appspot.com',
  );
}
